## Objective
In this project, my primary focus is on addressing insights related to Fleet Management and Supply Chain. To achieve this goal efficiently, the project has been divided into few objectives:

# Data Reading

In [1]:
# import the libraries
import pandas as pd
import re
from IPython.display import display, Markdown

There are excel workbooks so i had to extract the sheets of them and convert to csv so I can work on easly

In [14]:
excelPath="DimensionTables.xlsx"
excelFile = pd.ExcelFile(excelPath)
print(excelFile.sheet_names)

['Drivers', 'Vehicles', 'Customers']

In [15]:
for name in excelFile.sheet_names:
    df = pd.read_excel(excelPath, sheet_name=name)
    df.to_csv(f"{name}.csv", index=False, encoding="utf-8-sig")

In [9]:
excelPath2="fCosts.xlsx"
excelFile2 = pd.ExcelFile(excelPath2)
print(excelFile2.sheet_names)

['fKMTraveled']

In [ ]:
sheetName = excelFile2.sheet_names[0]
df = pd.read_excel(excelPath2, sheet_name=sheetName)
df.to_csv(f"{sheetName}.csv", index=False, encoding="utf-8-sig")

In [10]:
excelPath3="Dim States.xlsx"
excelFile3 = pd.ExcelFile(excelPath3)
print(excelFile3.sheet_names)

['STATES']

In [ ]:
sheetName = excelFile3.sheet_names[0]
df = pd.read_excel(excelPath3, sheet_name=sheetName)
df.to_csv(f"{sheetName}.csv", index=False, encoding="utf-8-sig")

In [63]:
# ===Reading Files===
F_Freight=pd.read_csv('fFreight.csv')
F_KMTraveled=pd.read_csv('fKMTraveled.csv')
D_Customers=pd.read_csv('Customers.csv')
D_Drivers=pd.read_csv('Drivers.csv')
D_STATES=pd.read_csv('STATES.csv')
D_Vehicles=pd.read_csv('Vehicles.csv')
tables_list = [
    ("F_Freight", F_Freight),
    ("F_KMTraveled", F_KMTraveled),
    ("D_Customers", D_Customers),
    ("D_Drivers", D_Drivers),
    ("D_STATES", D_STATES),
    ("D_Vehicles", D_Vehicles)
]

# Data Exploration

In [64]:
pd.set_option('display.max_columns', None)
pd.set_option('display.expand_frame_repr', False)
pd.set_option('display.width', 1500)

def auditData(df, fileName="Dataset"):
    display(Markdown(f"# 📊 Audit Report — `{fileName}`"))

    # Preview
    display(Markdown("## 👀 Preview"))
    display(df.head())

    # Basic Audit
    display(Markdown("## 🧱 Basic Audit"))

    # Schema + Missing Values
    schemaDf = pd.DataFrame({
        "Column": df.columns,
        "Non-Null Count": df.notna().sum().values,
        "Dtype": df.dtypes.values,
        "Missing Count": df.isna().sum().values
    })
    display(Markdown("### Schema & Missing Values"))
    display(schemaDf)

    # Duplicated Rows + Dataset Summary
    totalRows = len(df)
    totalCols = df.shape[1]
    dtypesSummary = ', '.join([f"{dt} {cnt}" for dt, cnt in df.dtypes.value_counts().items()])
    dupSummaryDf = pd.DataFrame({
        "Duplicated Rows": [df.duplicated().sum()],
        "Total Rows": [totalRows],
        "Total Columns": [totalCols],
        "Dtypes Summary": [dtypesSummary]
    })
    display(Markdown("### Duplicates & Dataset Summary"))
    display(dupSummaryDf)

    # Categorical Audit
    catCols = df.select_dtypes(include=['object', 'category', 'string']).columns
    if len(catCols):
        display(Markdown("## 🔤 Categorical Audit"))

        # Unique counts table
        uniqueCounts = {col: df[col].nunique(dropna=False) for col in catCols}
        display(Markdown("### Unique Counts per Column"))
        display(pd.DataFrame(uniqueCounts, index=["Unique Count"]).T)

        # Full unique values (wide display dynamic)
        for col in catCols:
            if not re.search(r'id|date|key|time', col, re.IGNORECASE):
                display(Markdown(f"### `{col}` — All Unique Values"))
                values = df[col].astype(str).unique()
                n_values = len(values)

                # Dynamic columns based on number of values
                ncols = max(5, int(n_values**0.5))  
                nrows = (n_values + ncols - 1) // ncols
                wideArr = [values[i*ncols:(i+1)*ncols] for i in range(nrows)]
                wideDf = pd.DataFrame(wideArr)
                display(wideDf.fillna(""))

                # Check spaces
                spaceDf = df.assign(
                    leadTrail=df[col].astype(str).str.len()
                              != df[col].astype(str).str.strip().str.len(),
                    doubleSpace=df[col].astype(str).str.contains(r'\s{2,}', regex=True)
                ).loc[
                    lambda x: x['leadTrail'] | x['doubleSpace'],
                    [col, 'leadTrail', 'doubleSpace']
                ].drop_duplicates()
                if not spaceDf.empty:
                    display(Markdown("⚠️ Space Issues"))
                    display(spaceDf)

    # Numerical Audit (Invalid + Quantiles)
    numCols = df.select_dtypes(include=['number']).columns
    if len(numCols):
        display(Markdown("## 🔢 Numerical Audit"))
        display(Markdown("### Statistics"))
        display(df[numCols].describe())

        # Prepare combined table: Invalid + quantiles
        combinedDict = {}
        for col in numCols:
            combinedDict[col] = [(df[col] <= 0).sum()] + df[col].quantile([0,0.01,0.25,0.5,0.75,0.99,1]).tolist()
        indexLabels = ["Invalid (<=0)", 0, 0.01, 0.25, 0.5, 0.75, 0.99, 1]
        combinedDf = pd.DataFrame(combinedDict, index=indexLabels)
        display(Markdown("### Invalid Values ⬅️➡️ Quantiles"))
        display(combinedDf)

    # Date & Time Audit 
    dateCols = list(set(
        df.select_dtypes(include=['datetime', 'datetimetz']).columns.tolist() +
        [c for c in df.columns if re.search(r'year|month|day|date|time', c, re.IGNORECASE)]
    ))
    if dateCols:
        display(Markdown("## 📅 Date & Time Audit"))
        for col in dateCols:
            if df[col].dtype in ['object', 'string', 'category']:
                tmp = pd.to_datetime(df[col], errors='coerce')
                if tmp.notna().any():
                    display(pd.DataFrame({
                        "column": [col],
                        "min": [tmp.min()],
                        "max": [tmp.max()]
                    }))
                else:
                    display(pd.DataFrame({
                        "column": [col],
                        "status": ["not date-parsable"]
                    }))
            else:
                # Numeric column: show min/max as is
                display(pd.DataFrame({
                    "column": [col],
                    "min": [df[col].min()],
                    "max": [df[col].max()]
                }))

# === Function to audit a list of DataFrames ===
def auditDataFrames(dfs_list):
    for name, df in dfs_list:
        auditData(df, name)


auditDataFrames(tables_list)

# 📊 Audit Report — `F_Freight`

## 👀 Preview

         Date  Customer ID  Truck ID  Invoice Number           Freight ID                 City  Net Revenue  Weight (Kg)  Weight (Cubic)  Goods Value
0  2018/01/02        10975        38          774571  02/01/2018:MMA-5946  Herrings Crossroads         7.42         2.50             3.0       247.39
1  2018/01/02        22346        23          774507  02/01/2018:MMA-4836               Enders         3.54         2.62             3.0       118.05
2  2018/01/02        12208        23          774516  02/01/2018:MMA-4836           Shavertown         8.98         5.54             9.0       299.01
3  2018/01/02         1929        23          774626  02/01/2018:MMA-4836               Enders        12.49         7.80             9.0       416.27
4  2018/01/02         6198        23          774623  02/01/2018:MMA-4836               Enders         2.49         8.55             9.0        82.90

## 🧱 Basic Audit

### Schema & Missing Values

           Column  Non-Null Count    Dtype  Missing Count
0            Date           92060   object              0
1     Customer ID           92060    int64              0
2        Truck ID           92060    int64              0
3  Invoice Number           92060    int64              0
4      Freight ID           92060   object              0
5            City           92060   object              0
6     Net Revenue           92060  float64              0
7     Weight (Kg)           92060  float64              0
8  Weight (Cubic)           92060  float64              0
9     Goods Value           92060  float64              0

### Duplicates & Dataset Summary

   Duplicated Rows  Total Rows  Total Columns                Dtypes Summary
0                0       92060             10  float64 4, object 3, int64 3

## 🔤 Categorical Audit

### Unique Counts per Column

            Unique Count
Date                 429
Freight ID          5032
City                 293

### `City` — All Unique Values

                      0                              1                       2                          3                         4                                5                                    6               7                    8                   9                   10                      11                     12                 13                   14                  15                              16
0    Herrings Crossroads                         Enders              Shavertown                New Freedom           Holcomb Village                          Kilgore                              Farmers           Loyce  Lake Harbor Estates             Mineola  Angola-on-the-lake          Orkney Springs           Banner Crest  Berkshire Heights              Newburg            Mcmechen                           Quinn
1            The Timbers                  Osborn Corner           Emerald Lakes               Clintonville             Arbor Meadows                     Yucca Valley                                 Pitt          Sparta  Chestnut Crossroads            Kaawaloa     Brighton Corner            Kenwood Park             River View               Page                Thorn               Bloom                       Wheatland
2                 Tarpey  Eastwood Subdivision Number 2                 Scammon                 Sandy Lane             Jewell Valley                        Applegate                               Sowash         Suwanee               Osborn                Ross   Dummerston Center                   Bryan                 Irving            Trammel               Greens           Sunnydale                         Goudeau
3                Dittmer                   Cave Springs               Carpenter                 Martindale                      Ball                           Moffat                              Bayport       Inglewood     Chancellorsville           Minnewawa         Spring City           Flora Heights            Rock Branch   Woodland Heights          Soradoville             Vanatta                      Oak Harbor
4      South Londonderry                   Beverly Cove           Beto Junction          Molasses Junction                  San Leon                      Tarnceville                         Kapp Heights    Davie Circle                 Lela     Lakeland Shores             Salinas          Mount Pleasant              Gambrinus           Stanhope             Lakeview              Ragley                  Powhatan Place
5             Ronkonkoma                    Jordanville               Cocoville            Clarkson Valley                 Woodcreek                      Glen Martin                              Conklin       Preakness          Aa Junction       Onset Station       West Ridgeway          Alfalfa Center           Lake Kathryn        Moose River         Hurd Corners           Woodstock                          Dooley
6        Wildcat Landing                   Moapa Valley  Chevington Woods North                     Ramsey           Inland Junction                    Pecan Terrace                                 Pink      Plainville                Sevey           Southmayd        Mount Hermon                   Beals                Elkview         Winkelmans              Speidel            Lee Mont  Maryland West Mobile Home Park
7             Gray Point                      Buggytown               Stony Run              Udall Landing                  Forester                       Boyne City                               Reaves    West Corners              Oreland        Hares Corner            Vandling                 Cadwell      Jerusalem Corners          Lowsville               Lollie     Sunrise Landing                          Balmat
8                Carroll                       Steprock                  Pomona             Fairfield Park              Cotton Place                        Flat Fork                               Neosho       Maplewood             Walsburg          Briarcrest      Gillman Bottom            Sand Springs                Wallace        Shore Acres        Sandy Corners             Teakean                    Denny Corner
9              Grandview                        Alpaugh                Graphite                       Elko                   Hawkeye                           Sharon  Raintree Equestrian Community Condo      Honeyville               Gilroy            Thompson             Warwick   Airport Road Addition                Labelle       South Berlin         Country Cove            Conlogue                        Moorhead
10  Rolling View Estates                  Saint Vincent             Five Points  Broken Ridge At Highpoint          Ballentine Manor                   Lithia Springs                        Gatewood Park  Sharon Springs            Selfville  Briar Lake Estates     Kuakini Heights                    Mint             Shellytown           Edenwold  Olde Federal Pointe  Jordan Point Manor                   Chestnut Hill
11              Belgrade                         Tipton             Gypsy Woods                 San Marino                    Beacon                           Leneve                         Independence        Tecumseh            Lake Lawn              Relief             Trimble            Poplar Ridge            Franklinton     Woodlawn Manor          Citrus City              Watson                        Stratham
12         Fairview Park                         Iberia                Briarton                Good Meadow                 Kingfield  Country Living Mobile Home Park                          Meadowlakes        Doniphan            Newfields              Munday       Mount Desales         Morrison Corner                Chukson        Llano Largo  Brownington Village        Everettville                       Coldwater
13             Greystone                        Lindsay                 De Soto             North Berkeley                Fairplains                       Shueyville        Lakewood Country Club Estates          Valona     Eason Crossroads          Estherwood         Frost Place                  Sidney            Tower Point             Jewett          Garden Park            Hometown                          Reuben
14                  Reno             Bald Hill Crossing           East Freetown                 Harrisburg  Grover Cleveland Terrace                       Piney View                      Just Crossroads          Hillje         Newfoundland              Nimrod      North Sandwich   Spring Valley Estates  Bear Lake Hot Springs        New Augusta    Grays Harbor City             Nokomis                  Waterloo Mills
15    Manning Crossroads                       Blessing                 Bruning                    Barland                    Valley                          Rapides                               Quinif     Meadowbrook              Hocking        Fayne Siding           Crestwood                Woodford                Deacons           Tulelake                Mason       Altamaha Park                        Waterloo
16         Fort Nonsense                    Briar Patch  Carysfort Yacht Harbor                  Big Trees                    Bertha                     Maple Valley                            Plainwell       Bay State           Pimaco Two           Cornelius           The Pines  Estates At Rivers Edge          Royalty Acres      Kincheonville               Lerona               Keyes                       Fair Oaks
17        Campbellsville                       Columbus             Sippewisset                  Telocaset

## 🔢 Numerical Audit

### Statistics

        Customer ID      Truck ID  Invoice Number   Net Revenue   Weight (Kg)  Weight (Cubic)    Goods Value
count  92060.000000  92060.000000    9.206000e+04  92060.000000  92060.000000    92060.000000   92060.000000
mean   20700.603009     26.656083    9.003256e+05     59.320266     86.610391      124.642261    1571.666272
std    12686.415364     11.477371    1.568757e+05    250.192940    430.979416      568.545570    6834.136249
min       10.000000      2.000000    4.507400e+04      0.010000      0.000000        0.000000       0.100000
25%     9308.000000     20.000000    8.465768e+05      5.800000      3.920000        6.000000     140.060000
50%    21331.000000     24.000000    9.254625e+05     13.925000     11.510000       17.360000     314.030000
75%    32162.000000     34.000000    9.907308e+05     38.410000     38.050000       57.000000     843.172500
max    43906.000000     45.000000    1.049972e+06  18579.180000  31748.000000    31748.000000  957357.990000

### Invalid Values ⬅️➡️ Quantiles

               Customer ID  Truck ID  Invoice Number  Net Revenue  Weight (Kg)  Weight (Cubic)  Goods Value
Invalid (<=0)         0.00       0.0            0.00        0.000       3.0000            3.00       0.0000
0                    10.00       2.0        45074.00        0.010       0.0000            0.00       0.1000
0.01                209.00       2.0        59479.59        0.080       0.1000            0.10       2.8900
0.25               9308.00      20.0       846576.75        5.800       3.9200            6.00     140.0600
0.5               21331.00      24.0       925462.50       13.925      11.5100           17.36     314.0300
0.75              32162.00      34.0       990730.75       38.410      38.0500           57.00     843.1725
0.99              43291.82      45.0      1047470.41      816.000    1437.8833         2116.23   20132.6610
1                 43906.00      45.0      1049972.00    18579.180   31748.0000        31748.00  957357.9900

## 📅 Date & Time Audit

  column        min        max
0   Date 2018-01-02 2019-08-31

# 📊 Audit Report — `F_KMTraveled`

## 👀 Preview

         Date  Truck ID  Drive ID  KM Traveled   Liters     Fuel  Maintenance   Fixed Costs
0  2018-01-01         2         2         4594  1303.06  4077.49      1011.93  10502.595165
1  2018-01-01         6         4         3816   899.14  2813.70      1561.78   6092.156655
2  2018-01-01        17         9         7116  2128.46  6491.00      1324.12  11930.903310
3  2018-01-01        19        11         2724   669.73  2123.58       560.17   7428.016155
4  2018-01-01        20        12         3862   723.02  2378.19       648.11   6735.388638

## 🧱 Basic Audit

### Schema & Missing Values

        Column  Non-Null Count    Dtype  Missing Count
0         Date             295   object              0
1     Truck ID             295    int64              0
2     Drive ID             295    int64              0
3  KM Traveled             295    int64              0
4       Liters             295  float64              0
5         Fuel             295  float64              0
6  Maintenance             295  float64              0
7  Fixed Costs             295  float64              0

### Duplicates & Dataset Summary

   Duplicated Rows  Total Rows  Total Columns                Dtypes Summary
0                0         295              8  float64 4, int64 3, object 1

## 🔤 Categorical Audit

### Unique Counts per Column

      Unique Count
Date            20

## 🔢 Numerical Audit

### Statistics

         Truck ID    Drive ID  KM Traveled       Liters         Fuel  Maintenance   Fixed Costs
count  295.000000  295.000000   295.000000   295.000000   295.000000   295.000000    295.000000
mean    22.400000   13.796610  3993.416949   912.331220  3057.270814   906.462712   8821.506132
std     12.572619    9.573524  1625.631686   508.447627  1700.681990   486.064968   2765.854491
min      2.000000    1.000000     0.000000     0.000000     0.000000   256.350000   5184.415638
25%     17.000000    5.000000  2629.000000   525.770000  1821.735000   525.825000   7165.503888
50%     22.000000   12.000000  4127.000000   795.670000  2739.900000   759.180000   7763.266740
75%     33.000000   23.000000  5047.000000  1160.890000  3897.720000  1256.990000   9906.549165
max     45.000000   31.000000  8476.000000  2958.240000  9498.930000  3755.550000  19984.350000

### Invalid Values ⬅️➡️ Quantiles

               Truck ID  Drive ID  KM Traveled     Liters       Fuel  Maintenance   Fixed Costs
Invalid (<=0)       0.0       0.0         3.00     3.0000     3.0000       0.0000      0.000000
0                   2.0       1.0         0.00     0.0000     0.0000     256.3500   5184.415638
0.01                2.0       1.0        70.50    25.8124    85.9536     294.5968   6013.953767
0.25               17.0       5.0      2629.00   525.7700  1821.7350     525.8250   7165.503888
0.5                22.0      12.0      4127.00   795.6700  2739.9000     759.1800   7763.266740
0.75               33.0      23.0      5047.00  1160.8900  3897.7200    1256.9900   9906.549165
0.99               45.0      31.0      7601.06  2277.3488  7828.7400    1956.5748  19491.741000
1                  45.0      31.0      8476.00  2958.2400  9498.9300    3755.5500  19984.350000

## 📅 Date & Time Audit

  column        min        max
0   Date 2018-01-01 2019-08-01

# 📊 Audit Report — `D_Customers`

## 👀 Preview

   Customer ID     City State  Latitude  Longitude
0            5  Mineola    KY   38.8881   -91.5714
1            6  Mineola    KY   38.8881   -91.5714
2           21  Mineola    KY   38.8881   -91.5714
3           34  Mineola    KY   38.8881   -91.5714
4           43  Mineola    KY   38.8881   -91.5714

## 🧱 Basic Audit

### Schema & Missing Values

        Column  Non-Null Count    Dtype  Missing Count
0  Customer ID           43910    int64              0
1         City           43910   object              0
2        State           43910   object              0
3     Latitude           43910  float64              0
4    Longitude           43910  float64              0

### Duplicates & Dataset Summary

   Duplicated Rows  Total Rows  Total Columns                Dtypes Summary
0                0       43910              5  object 2, float64 2, int64 1

## 🔤 Categorical Audit

### Unique Counts per Column

       Unique Count
City            550
State            51

### `City` — All Unique Values

                    0                  1                              2                3                                4                              5                       6                             7                       8                9                     10                             11                12                  13                   14                      15                        16                         17                   18                             19                                   20                   21                              22
0              Mineola              Bloom            Herrings Crossroads           Enders                        Wheatland                   Yucca Valley             Tower Point                    Sandy Lane            Banner Crest          Suwanee                Neosho                       Mcmechen        Shavertown    Woodland Heights                 Pitt          Lithia Springs                   Trammel                       Ball             Lee Mont                  Sandy Corners  Raintree Equestrian Community Condo  Lake Harbor Estates                 Holcomb Village
1                Loyce         Martindale                 North Sandwich  Brighton Corner                             Pink                 Orkney Springs             Llano Largo                        Osborn                 Kilgore    Udall Landing             Cocoville                         Irving          Kaawaloa           Kingfield          Rock Branch                 Speidel                Boyne City                     Relief        Pecan Terrace                Kuakini Heights                               Moffat            Minnewawa                          Watson
2             Thompson             Reaves                         Sowash            Sevey                     Beverly Cove                        Alpaugh      Manning Crossroads               Inland Junction           Flora Heights             Elko         Arbor Meadows                   Kenwood Park    Powhatan Place         New Freedom             Stanhope                    Reno                 Crestwood                   Steprock              Teakean                        Wallace                             San Leon      Wildcat Landing                  Sharon Springs
3              Salinas             Jewett              Dummerston Center           Greens                          Bruning                Just Crossroads          Fairfield Park                        Iberia              West Tulsa          Deacons           Los Fuertes                    Moose River            Balmat       Saint Vincent          Glen Martin                   Arvel  Grover Cleveland Terrace                     Lollie          Soradoville                        Vanatta                          Good Meadow            Woodstock                    Kapp Heights
4          Sippewisset       Maple Valley                         Ragley      Spring City                      Citrus City                        Chukson                La Junta                      Walsburg                 De Soto      Garden Park            Piney View                     Honeyville         Maplewood   Jerusalem Corners             Belgrade            Hares Corner                   Campion                     Beacon            Southmayd                        Hawkeye                             Waterloo              Mozelle                       Big Trees
5            Stony Run        Jordanville                Morrison Corner          Barland                          Labelle                      Sunnydale  Estates At Rivers Edge                Alfalfa Center                 Newburg            Hamby              Graphite                 Antelope Hills     Chestnut Hill        Lake Kathryn            Buggytown             Five Points                 Greystone                   Vandling         Clintonville                         Tarpey                            Inglewood       North Berkeley                      Harrisburg
6          Franklinton           Briarton                     Estherwood     Sand Springs                       Briarcrest              Berkshire Heights                 Carroll                          Mint              Shellytown  Sunrise Landing     South Londonderry                         Pomona          Stratham  Briar Lake Estates  Chestnut Crossroads              River View                     Thorn              Gatewood Park              Warwick                   Poplar Ridge                        Fairview Park         Cotton Place                Ballentine Manor
7               Tipton  Molasses Junction                         Sparta         Tulelake                           Gilroy                      Starfield                  Hillje                          Ross                 Elkview            Keyes            Gray Point                      Selfville     Altamaha Park               Bryan            Grandview              San Marino                 Tenstrike  Broken Ridge At Highpoint         Moapa Valley          Bear Lake Hot Springs                           Winkelmans          Aa Junction                       Carpenter
8            Lowsville            Cadwell          Airport Road Addition     Independence                     Newfoundland                         Ramsey            Hurd Corners                 Erie Junction  Chevington Woods North      Shore Acres          West Corners                Clarkson Valley       The Timbers  Bald Hill Crossing           Fairplains              Pimaco Two       Olde Federal Pointe                      Beals        Kincheonville                        Conklin                           Plainville               Hardin                  Woodlawn Manor
9             Florence        Frost Place               Eason Crossroads   Gillman Bottom  Country Living Mobile Home Park                      Bay State          Mount Pleasant                 Beto Junction               Plainwell        Coldwater               Scammon                   Everettville            Reuben          Gandertown             Hometown           Osborn Corner                    Dooley                 Ronkonkoma         Country Cove                        Dittmer                                Mason              Rapides  Maryland West Mobile Home Park
10  Angola-on-the-lake          Cornelius                       Conlogue          Hocking                       Rivers End                      Flat Fork                Edenwold                       Lindsay           Royalty Acres          Hospers  Rolling View Estates                  Mount Desales      Mount Hermon              Quinif               Sidney  Carysfort Yacht Harbor             West Ridgeway           Epworth Assembly             Moorhead                   South Berlin                            Newfields              Oreland                       Windemere
11         Elgin Farms           Frog Eye  Eastwood Subdivision Number 2    East Freetown                           Sharon                      Woodcreek                Blessing                      Tecumseh               Preakness        The Pines           Gypsy Woods                    Briar Patch  Chancellorsville              Leneve        Fort Nonsense            Cave Springs     Spring Valley Estates                    Pyrmont               Forest                   Fayne Siding                            Telocaset           East Islip                         Gordola
12              French             Bertha                       Woodford  Lower Gilmanton                    Lake Waccamaw                         Valley                   March  Pepper Tree Mobile Home Park   Silver Spring Station     Denny Corner               Trimble             Jordan Point Manor          Lakeview           Applegate            Gambrinus                  Lerona       Brownington Village              Jewell Valley          Tarnceville                     Oak Harbor                            Englewood              Goudeau                       Dungannon
13             Bayport          Fair Oaks                          Quinn             King                             Page                         Nimrod             Meadowbrook                     Lake Lawn            Rustic Acres    Emerald Lakes                 Wendt                        Farmers              Lela           Goodridge               Weldon            Hopkinsville                 Westfield                   Lewiston      Lakeland Shores                     Shueyville                                Globe               Colony                       Thornburg
14      Listening Rock              Carne                      Franconia            Diana                        Leicester                      Bowentown                 Sulphur                      Kumukumu            Pickettville      Seba Dalkai         Cribbs Corner                      Berrytown       Browns Mill          Cedar Fort           Tylersport                   Curry                   Beachly               Coulterville        Wheelockville                        Woodlyn                             Prentiss         Gilford Park                        Narberth
15       Country Manor    Smithwood Manor                      Cain City     Ryan Village                    Johnstonville  Lakewood Country Club Estates                Holstein                 Spanish Grove          Celeste Hinkel         Pickaway              Edgeboro  Quail Hollow Mobile Home Park    Dawson Springs           Northwood                Fried                   Sloan          Carpenter Hollow                      Faris                 Ohio                        Boykins                           Larsen Bay           Old Lawton                         Tibbets
16            Grinnell             Cedron                     Hagerville          Oakmont                            Ryors                    Bargaintown          Sycamore Ridge                        Thomas             Golden Lake            Vicey             New Glatz                    New Augusta       Rankin Cove             Vidrine              Jackson               Frederick       Copper Cove Village              Onset Station        Stemlersville                   Sugar Valley                            Princeton             Hartford                           Arles
17       Stillmanville              Turin                      Roseville           Beegum                        Dunn Mill                      Watterson              Flat Creek            Ann Wrights Corner               Pike City      Mud Springs   Forest Hill Village                   Newmansville            Tulane             Mcnally            Haverhill           Dupont Center                      Eddy                  New Italy               Comorn       Lebruns Mobile Home Park                           Mount Zion             Ridgeway               Arlington Heights
18      Emerson Corner          Riverside                         Gordon  Bellville Point                         Scottown                        Mayline         Darrough Chapel                   Brownsville          Waterloo Mills            Gwinn                Malone              Lockhart Junction   Cienega Springs             Nokomis    Grays Harbor City                 Bluegum                   Delight               Balsam Grove             Forester                        Johnson                                Hines              Beasley             Lake Prince Meadows
19        Warners Mill     West Fitchburg                     Willowbend           Munday                         Doniphan           Four Seasons Estates                  Valona                      Guthries            Davie Circle      Meadowlakes                 Pungo                East Charleston   Highway Village           Lena Park            Ridgeview                 Pinhook          Benwood Junction                 Stringtown  Stone Hedge Estates           Falcon Ridge Estates                               Choate    Speck Subdivision                          Nakina
20              Cotuit             Putney                      New Grove              Ely                           Bucoda                         Latham           New Cleveland                   Drakesville                Oklahoma   Greenway Court               Tomales                       Oakridge           Palermo        Dutch Harbor             Brainard              Turbeville                 Extension                      Joice      New Berlinville                 South Danville                          Grand Ecore               Willow                          Stroud
21           Fruitdale            Kashmir                          Fuson           Moyers                        Pendleton                   Popple Creek             Marks Place                     Keenbrook             Muttonville        Woolworth              Linworth                      Salemburg    Kent Woodlands            Vacherie       Spokane Valley           Ringing Hills              Stephens Gap                Arden Mines          Spring Lake  Bethany Cooperative Community                             Eggville           Shenandoah                         Mcgowan
22       New Kingstown  Rum Ridge Estates                      Coalfield      Piercefield                           Coloma                         Wilson                   Avery                       Nesmith                 Decatur       Bush Manor               Renfroe                       Gold Run        Savin Rock    Ridgeview Forest                Milne  High Point Subdivision          Frankfort Center                       Call         Eustacestown               Summerland Beach        Orchard Lane Mobile Home Park     Highland Meadows                     Cedar Grove
23           Glen Isle              Gheen                          Sutro      Dauberville                         Columbus            Hidden Valley Homes                  Banner                    New Athens                  Holden           Questa        Campbellsville                       Hilltown          Cromwell          Smith Ford           Walterhill                Dreahook             Schiller Park                      Naola       Normandy Woods                   Hidden Ridge                            Dalecrest

### `State` — All Unique Values

    0   1   2   3   4   5   6
0  KY  SC  OK  WV  WY  MI  MN
1  VT  AZ  KS  NC  MS  IL  WI
2  NV  MD  MO  AR  AK  DE  SD
3  ME  TN  OH  WA  AL  OR  MT
4  CA  MA  IA  TX  NY  LA  FL
5  NM  NE  IN  GA  CO  CT  NH
6  HI  NJ  ID  ND  VA  DC  UT
7  PA  RI

## 🔢 Numerical Audit

### Statistics

        Customer ID      Latitude     Longitude
count  43910.000000  43910.000000  43910.000000
mean   21955.500000     37.216962    -89.823250
std    12675.869497      4.654828     13.842232
min        1.000000     19.482500   -166.511000
25%    10978.250000     34.765300    -98.296100
50%    21955.500000     37.635600    -88.281100
75%    32932.750000     39.825600    -77.900300
max    43910.000000     57.540000    -68.583600

### Invalid Values ⬅️➡️ Quantiles

               Customer ID  Latitude   Longitude
Invalid (<=0)         0.00    0.0000  43910.0000
0                     1.00   19.4825   -166.5110
0.01                440.09   28.3803   -123.0590
0.25              10978.25   34.7653    -98.2961
0.5               21955.50   37.6356    -88.2811
0.75              32932.75   39.8256    -77.9003
0.99              43470.91   47.7439    -70.6733
1                 43910.00   57.5400    -68.5836

# 📊 Audit Report — `D_Drivers`

## 👀 Preview

   Driver ID          Driver
0          1       No Driver
1          2  Ridwan Greaves
2          3     Efan Archer
3          4     Karol Woods
4          5      Amman Vega

## 🧱 Basic Audit

### Schema & Missing Values

      Column  Non-Null Count   Dtype  Missing Count
0  Driver ID              32   int64              0
1     Driver              32  object              0

### Duplicates & Dataset Summary

   Duplicated Rows  Total Rows  Total Columns     Dtypes Summary
0                0          32              2  int64 1, object 1

## 🔤 Categorical Audit

### Unique Counts per Column

        Unique Count
Driver            32

### `Driver` — All Unique Values

                 0                    1                 2                 3                4
0        No Driver       Ridwan Greaves       Efan Archer       Karol Woods       Amman Vega
1       Sol Porter         Nikola Weiss  Tierney Reynolds  Kenzie Macdonald      Anton Garza
2  Maheen Nicholls     Stevie Schofield         Asha Cruz        Yasin Buck        Ubaid Key
3     Idris Alston          Axel Hodges    Kailum Ellison      Arianne Rosa  Montell Winters
4    Arslan Cooley  Salahuddin Arellano    Frederick Watt    Marcel Wormald       Gino Boone
5        Nora Kerr           Kenny Todd      Kaan Markham    Percy Mcnamara    Kiah O'Connor
6     Riyad Harris      Kymani Sharples

## 🔢 Numerical Audit

### Statistics

       Driver ID
count  32.000000
mean   16.500000
std     9.380832
min     1.000000
25%     8.750000
50%    16.500000
75%    24.250000
max    32.000000

### Invalid Values ⬅️➡️ Quantiles

               Driver ID
Invalid (<=0)       0.00
0                   1.00
0.01                1.31
0.25                8.75
0.5                16.50
0.75               24.25
0.99               31.69
1                  32.00

# 📊 Audit Report — `D_STATES`

## 👀 Preview

    Full Name Abbreviation  Index
0     Alabama           AL      0
1      Alaska           AK      1
2     Arizona           AZ      2
3    Arkansas           AR      3
4  California           CA      4

## 🧱 Basic Audit

### Schema & Missing Values

         Column  Non-Null Count   Dtype  Missing Count
0     Full Name              51  object              0
1  Abbreviation              51  object              0
2         Index              51   int64              0

### Duplicates & Dataset Summary

   Duplicated Rows  Total Rows  Total Columns     Dtypes Summary
0                0          51              3  object 2, int64 1

## 🔤 Categorical Audit

### Unique Counts per Column

              Unique Count
Full Name               51
Abbreviation            51

### `Full Name` — All Unique Values

               0                     1             2             3               4              5              6
0        Alabama                Alaska       Arizona      Arkansas      California       Colorado    Connecticut
1       Delaware               Florida       Georgia        Hawaii           Idaho       Illinois        Indiana
2           Iowa                Kansas      Kentucky     Louisiana           Maine       Maryland  Massachusetts
3       Michigan             Minnesota   Mississippi      Missouri         Montana       Nebraska         Nevada
4  New Hampshire            New Jersey    New Mexico      New York  North Carolina   North Dakota           Ohio
5       Oklahoma                Oregon  Pennsylvania  Rhode Island  South Carolina   South Dakota      Tennessee
6          Texas                  Utah       Vermont      Virginia      Washington  West Virginia      Wisconsin
7        Wyoming  District of Columbia

### `Abbreviation` — All Unique Values

    0   1   2   3   4   5   6
0  AL  AK  AZ  AR  CA  CO  CT
1  DE  FL  GA  HI  ID  IL  IN
2  IA  KS  KY  LA  ME  MD  MA
3  MI  MN  MS  MO  MT  NE  NV
4  NH  NJ  NM  NY  NC  ND  OH
5  OK  OR  PA  RI  SC  SD  TN
6  TX  UT  VT  VA  WA  WV  WI
7  WY  DC

## 🔢 Numerical Audit

### Statistics

           Index
count  51.000000
mean   25.000000
std    14.866069
min     0.000000
25%    12.500000
50%    25.000000
75%    37.500000
max    50.000000

### Invalid Values ⬅️➡️ Quantiles

               Index
Invalid (<=0)    1.0
0                0.0
0.01             0.5
0.25            12.5
0.5             25.0
0.75            37.5
0.99            49.5
1               50.0

# 📊 Audit Report — `D_Vehicles`

## 👀 Preview

   Truck ID     Plate Brand    Truck Type Trailers Type  Year
0         2  MJD-6976    VW  SEMI-TRAILER        Reefer  2011
1         3  MJT-4829    VW  SEMI-TRAILER        Reefer  2010
2         4  MHJ-9634    VW       TRAILER        Reefer  2009
3         5  MKP-6610    VW       TRAILER        Reefer  2006
4         6  MHN-5539    VW           BOX        Fridge  2010

## 🧱 Basic Audit

### Schema & Missing Values

          Column  Non-Null Count   Dtype  Missing Count
0       Truck ID              31   int64              0
1          Plate              31  object              0
2          Brand              31  object              0
3     Truck Type              31  object              0
4  Trailers Type              31  object              0
5           Year              31   int64              0

### Duplicates & Dataset Summary

   Duplicated Rows  Total Rows  Total Columns     Dtypes Summary
0                0          31              6  object 4, int64 2

## 🔤 Categorical Audit

### Unique Counts per Column

               Unique Count
Plate                    31
Brand                     1
Truck Type                4
Trailers Type             3

### `Plate` — All Unique Values

          0         1         2         3         4
0  MJD-6976  MJT-4829  MHJ-9634  MKP-6610  MHN-5539
1  MJT-5239  MJI-0517  MLX-5112  MDB-1602  MML-5482
2  MMA-5936  MMA-5926  MMA-4836  MMA-5916  MMA-5906
3  MJB-2591  MHQ-9301  MML-3632  MJA-4001  MKU-5802
4  MHN-5439  MHJ-2813  MHR-5525  MFU-2632  MMA-5946
5  MHR-5515  MHJ-0053  QJP-8750  QJP-8770  QJP-8860
6  QJP-8960

### `Brand` — All Unique Values

    0
0  VW

### `Truck Type` — All Unique Values

              0        1    2        3
0  SEMI-TRAILER  TRAILER  BOX  TRACTOR

### `Trailers Type` — All Unique Values

        0       1    2
0  Reefer  Fridge  Dry

## 🔢 Numerical Audit

### Statistics

        Truck ID         Year
count  31.000000    31.000000
mean   25.709677  2012.129032
std    13.249386     3.490386
min     2.000000  2006.000000
25%    18.500000  2009.000000
50%    27.000000  2013.000000
75%    36.500000  2014.000000
max    45.000000  2019.000000

### Invalid Values ⬅️➡️ Quantiles

               Truck ID    Year
Invalid (<=0)       0.0     0.0
0                   2.0  2006.0
0.01                2.3  2006.6
0.25               18.5  2009.0
0.5                27.0  2013.0
0.75               36.5  2014.0
0.99               44.7  2019.0
1                  45.0  2019.0

## 📅 Date & Time Audit

  column   min   max
0   Year  2006  2019

# Data Summary

The dataset provides many data tables including freights and their costs , customers and their states, drivers and their vehicles. After examining the data fields, I noticed that the dataset generally represents the following key information

* Customer: General information about customers including identifiers and addresses

* drivers: Information about drivers including identifiers and names

* vehicles: Vehicles information including Plate, brand, year of manufacturing and truck&trailer types

* Freights: Every frieght with information about costs, revenue, kms, weights, truck used and the city it went to

We found invalid values here: weights are zero however revenue and goods value are not

In [65]:
F_Freight[F_Freight['Weight (Kg)']==0]

             Date  Customer ID  Truck ID  Invoice Number           Freight ID       City  Net Revenue  Weight (Kg)  Weight (Cubic)  Goods Value
19238  2018/06/04         3250        19          841074  04/06/2018:MDB-1602  Minnewawa        63.86          0.0             0.0       884.40
26386  2018/08/02        31836        19          867643  02/08/2018:MDB-1602    Mineola        63.86          0.0             0.0       810.94
76344  2019/06/13         1600        22         1010816  13/06/2019:MMA-5926     Sowash        93.98          0.0             0.0      2100.00

I think those days are for meintenance only

In [66]:
F_KMTraveled[F_KMTraveled['KM Traveled']==0]

           Date  Truck ID  Drive ID  KM Traveled  Liters  Fuel  Maintenance  Fixed Costs
17   2018-01-01        34         1            0     0.0   0.0       929.45  7212.140655
123  2018-07-01         5         1            0     0.0   0.0      1140.86  7293.480138
142  2018-08-01        37        26            0     0.0   0.0       488.77  6117.121100

We found half of data geting weight (kg) = weight(Cubic)

so i think cubic is only duplicate of the kg so we won't depend on this column

In [67]:
mask = (F_Freight['Weight (Kg)'] == F_Freight['Weight (Cubic)'])
f"{mask.mean() * 100:.2f}%"

'49.63%'

We found some big values in data so we checked them

In [ ]:
F_Freight[F_Freight['Goods Value']>450000]
''' 
Goods Value is 4,987.6 for each kg, that is very big 
Maybe They are expensive Electronics
'''

             Date  Customer ID  Truck ID  Invoice Number           Freight ID    City  Net Revenue  Weight (Kg)  Weight (Cubic)  Goods Value
67679  2019/05/02        22719        23          990576  02/05/2019:MMA-4836  Enders     17301.65        192.1           192.1    957357.99

In [ ]:
F_Freight[F_Freight['Weight (Kg)']>30000]
''' 
Goods Value is 0.038 for each kg, that is very small 
Maybe They are Inexpensive raw materials: Sand, gravel, cement, non-precious metal ores
'''

             Date  Customer ID  Truck ID  Invoice Number           Freight ID         City  Net Revenue  Weight (Kg)  Weight (Cubic)  Goods Value
13815  2018/04/16          169        33          821503  16/04/2018:MKU-5802  Spring City     15492.95      31748.0         31748.0       1206.7

We also found date columns to be object type so we have to change it to datetime

# Data Transformation and Cleaning

We need to do type casting for date column from object to datetime

In [71]:
F_KMTraveled['Date'] = pd.to_datetime(F_KMTraveled['Date'], errors='coerce')
F_Freight['Date'] = pd.to_datetime(F_Freight['Date'], errors='coerce')

Since values that have weights zero are only 3 and that is very small percentage of total, we will drop them

In [72]:
mask = (F_Freight['Weight (Kg)'] == 0) & (F_Freight['Weight (Cubic)'] == 0)
F_Freight = F_Freight.loc[~mask]

# Feature Metrics
The feature metrics that planning to create in Power BI which helps to further analyze Drivers, Customers, Revenue and many more.

### Total Costs

Total Costs is a significant financial metric in supply chain management that calculates the overall cost associated with Maintenance, Fuel, Fixed Costs.

The formula for calculating Total Inventory Cost is: Sum of`Maintenance cost` + Sum of`Fuel Cost` + Sum of`Fixed Cost`.

#### Shipment Delay in Days
Shipment Delay  = [Shipment Days - Actual] - ['Shipment Days - Scheduled']

### Net Profit and Profit Margin

Profit Margin helps to assessing the profitability of the supply chain operations. It provides insights into the effectiveness of cost control and pricing strategies, enabling organizations to make adjustments to enhance overall profitability.

Profit Margin : Net Profit / Total Revenue *100

### Drivers Efficiency

`Avg Fuel consumption per km`, `Avg Fuel efficiency`, and `Avg Fuel cost per km` for each driver

Avg Fuel efficiency  = Total KMs traveled / Literes Consumed

Avg Fuel consumption per km = Literes Consumed / Total KMs traveled

Avg Fuel cost per km = Fuel Cost / Total KMs traveled

### Customer Retention

Customer Retention helps to find which Customers who return to make multiple orders

% Customer with multiple orders = repeated customers / active customers

# Data Exporting & Conclusion

## Exporting Cleaned Data

Save the cleaned and processed DataFrames to a csv file for further visualization and analysis in Power BI.

In [73]:
# Export DataFrames to CSV
F_Freight.to_csv('F_Freight.csv', index=False)
F_KMTraveled.to_csv('F_KMTraveled.csv', index=False)
D_Customers.to_csv('D_Customers.csv', index=False)
D_Drivers.to_csv('D_Drivers.csv', index=False)
D_STATES.to_csv('D_STATES.csv', index=False)
D_Vehicles.to_csv('D_Vehicles.csv', index=False)

## Conclusion

Through this analysis, we successfully explored and performed data cleaning on the `F_Freight` and `F_KMTraveled` DataFrames. Important metrics and Kpis such as `Total Revenue`, `Total Costs` `Net Proft` and their %YoY vs PY

 `Avg Fuel consumption per km`, `Avg Fuel efficiency`, and `Avg Fuel cost per km` for each driver will be calculated in Power BI to understand Fleet Management performance and supply chain efficiency for the company.

Additionally, we removed some anomalous data points that could impact the analysis results. The cleaned and processed data will be exported to a csv file for further analysis and visualization in Tableau.

## Closing

As an aspiring data engineer/data analyst, I will consistently look for opportunities to improve my skills and insights.Thank you so much.

This analysis was conducted on Khnown Data Set by Kaggle, with the aim of demonstrating data analytics expertise and providing actionable insights to address real-world business challenges. Throughout this process, I strive to use effective data processing, data cleaning, and advanced analytics techniques to generate meaningful conclusions and support decision making.